---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

    - name: Add all the (third party) packages needed for operation
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
          - gdebi-core
