language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r common/requirements.txt
- pip install -r osmocom-python/requirements.txt -r osmocom-python/requirements-dev.txt
sudo: false
script:
- nosetests --where common
- nosetests --where osmocom-python
- nosetests --where smspdu
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: dtHYX0hncSgXsLPyylaqRgYiqRlF4fYVMG2YmtOXKNAo+SdGBRHMgyJRB4gqJSMZ/BpBVhAL9f2C22Aw1xZ1ORYSRSawfcJgMAS5alh5fcE0ddJg3SG4UGXEUHkBYVq+j5qKfnNP6SnHzlL082chSWT8jIptJwcuiQpSSC212BgRwzJECTa2uGvafHbxFvDdF+osO7lSQ0nw9Vy2n2v3RXnkSnNAGF8X8iFr8a3ihXf6B3e0RJZY4KXpHGx1yPx62sH6LZNJfRljLAvCrKTOVfH7Tp6HUcw49F4+09VXwdir9OwCXd67AXQHGwZr3PQg07LGAIjb4t5Jl0zm48px0okf0FeEQznzEtQhMRPUHyFWI7qJWfgmBAf4GMWK84ZTlxxXuMzbUFYDWi7Mfue28O2ca0uWIvZ3Vy9zxsL7c7lY5WIaZbTJ0jVq0qlNqSmbJKFDmCVaLqF+zTttqV5uAwxctrU/NqfLHLevy3OUo3ew6pfoCQn4NXVwwvVoMqp0T1r9Msj51h9Wdei1rkQWuqGdNdDlAeNEsIv5J9kfpu688k603mN4//cD4a9E546uAWfRpGCKnzR9zVus/EdpCBX3RxzlnvHHBBh4vSxhGgrZvxGxpUwRiHcjOP4Ec+dBuce4ts263I+F2Db/RZKGcvVW4YUwqFvPpZRkSqXLQqc=
