---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# the native Ansible 'gem' module doesn't seem to work, and 'gem install'
# takes a while, so check if fpm is already installed
- name: Check whether FPM already installed
  command: fpm --version
  ignore_errors: true
  register: fpm_check
- name: Install FPM
  command: gem install fpm
  when: fpm_check | failed
