---
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- hosts: cert
  become: yes
  roles:
    - setup_fpm
    - { role: python_packages, pkgs: [ envoy, web.py ] }
    - { role: system_packages, pkgs: [ git, supervisor ] }
  post_tasks:
  # first build the package and push it to the keyserver
  - name: Copy over certifier
    copy: src=../certifier dest=/tmp/
    become: no
  - include: key-check.yml
    vars:
      cafile: '/tmp/certifier/etage-bundle.crt'
      cert: '/tmp/certifier/pki/ca.crt'
      key: '/tmp/certifier/pki/private/ca.key'
  - name: Get version
    command: cat /tmp/certifier/VERSION
    become: no
    register: cert_version
  - name: Build certifier package
    command: fpm -s dir -t deb -n certifier -v {{cert_version.stdout}} /tmp/certifier=/home/vagrant/
    ignore_errors: yes
    become: no
  # now that the package is deployed, set it up and start running it.
  - name: Install certifier
    apt: deb=certifier_{{cert_version.stdout}}_amd64.deb state=installed
  - name: Remove certifier package
    file: path=certifier_{{cert_version.stdout}}_amd64.deb state=absent
    become: no
  - name: Remove certifier directory
    file: path=/tmp/certifier state=absent
    become: no
  # add easyrsa
  - name: add easyrsa repo
    git: repo=https://github.com/OpenVPN/easy-rsa.git dest=/home/vagrant/easyrsa update=yes
  - name: copy easyrsa
    command: cp /home/vagrant/easyrsa/easyrsa3/easyrsa /home/vagrant/certifier/
  - name: easyrsa permissions
    file: path=/home/vagrant/certifier/easyrsa mode=a+x
  - name: Make sure that the config directory exists for supervisor
    file: path=/etc/supervisor/conf.d state=directory
  - name: Add supervisor config files
    copy: src=files/supervisor/supervisord.conf dest=/etc/supervisor/supervisord.conf
  - name: Add certifier config files
    copy: src=files/supervisor/conf.d/certifier.conf dest=/etc/supervisor/conf.d/certifier.conf
  - name: Change directory for supervisor
    replace: dest=/etc/supervisor/conf.d/certifier.conf regexp='ubuntu' replace='vagrant'
  - name: Make sure supervisor is running
    service: name=supervisor state=restarted
  - name: Make sure certifier is running
    supervisorctl: name=certifier state=restarted
